### ISSUE TITLE
Investigar o por que temos dois produtos em gerenciar

### ISSUE THREAD

**Issue by alexandrejuk** [realponto-project/stock-rp-front#39]
### descrição 
Investigar por que temos dois produtos em gerenciar e verificar qual estamos usando e se faz sentido ter ele em gerenciar

**Comment by jessiLeandro** [comment]
A pasta Produto continha a pagina em que era feito o gerenciamento de produto, fornecedor, usuário e técnico, enquanto a pasta GerenciarProduto é a pasta onde continha a página para atualizar que o usuário era redirecionado ao clicar em editar um dado produto através da página de gerenciamento.
